# Generated by Django 6.0.3 on 2026-03-15 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nama Proyek')),
                ('location', models.CharField(max_length=300, verbose_name='Lokasi')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('status', models.CharField(choices=[('perencanaan', 'Perencanaan'), ('aktif', 'Aktif'), ('selesai', 'Selesai'), ('ditunda', 'Ditunda')], default='aktif', max_length=20, verbose_name='Status')),
                ('total_units', models.PositiveIntegerField(default=0, verbose_name='Total Unit')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Target Selesai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(limit_choices_to={'role': 'developer'}, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyek',
                'verbose_name_plural': 'Proyek',
                'ordering': ['-created_at'],
            },
        ),
    ]
