# Generated by Django 6.0.3 on 2026-06-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_organization_alter_project_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='developer',
        ),
    ]
