# Generated by Django 6.0.3 on 2026-06-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='amdal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal AMDAL'),
        ),
        migrations.AddField(
            model_name='project',
            name='amdal_status',
            field=models.CharField(choices=[('belum', 'Belum Dimulai'), ('proses', 'Sedang Diproses'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='belum', max_length=20, verbose_name='Status AMDAL/UKL-UPL'),
        ),
        migrations.AddField(
            model_name='project',
            name='ipr_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal IPR'),
        ),
        migrations.AddField(
            model_name='project',
            name='ipr_status',
            field=models.CharField(choices=[('belum', 'Belum Dimulai'), ('proses', 'Sedang Diproses'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='belum', max_length=20, verbose_name='Status IPR'),
        ),
        migrations.AddField(
            model_name='project',
            name='master_plan_url',
            field=models.URLField(blank=True, verbose_name='URL Master Plan'),
        ),
        migrations.AddField(
            model_name='project',
            name='pbg_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal PBG Diterbitkan'),
        ),
        migrations.AddField(
            model_name='project',
            name='pbg_status',
            field=models.CharField(choices=[('belum', 'Belum Dimulai'), ('proses', 'Sedang Diproses'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='belum', max_length=20, verbose_name='Status PBG'),
        ),
        migrations.AddField(
            model_name='project',
            name='site_plan_url',
            field=models.URLField(blank=True, verbose_name='URL Site Plan'),
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('perencanaan', 'Perencanaan'), ('perizinan', 'Perizinan'), ('konstruksi', 'Konstruksi'), ('penjualan', 'Penjualan'), ('serah_terima', 'Serah Terima'), ('selesai', 'Selesai'), ('ditunda', 'Ditunda')], db_index=True, default='draft', max_length=20, verbose_name='Tahap'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Target Anggaran (Rp)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Target Selesai'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Mulai'),
        ),
    ]
