# Generated by Django 6.0.3 on 2026-06-24 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_status_project_amdal_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='readiness_score_last',
            field=models.IntegerField(default=0, verbose_name='Readiness Score Sebelumnya'),
        ),
        migrations.AddField(
            model_name='project',
            name='readiness_score_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Readiness Score Diperbarui'),
        ),
        migrations.CreateModel(
            name='StageRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('perencanaan', 'Perencanaan'), ('perizinan', 'Perizinan'), ('konstruksi', 'Konstruksi'), ('penjualan', 'Penjualan'), ('serah_terima', 'Serah Terima'), ('selesai', 'Selesai')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=200, verbose_name='Nama Requirement')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Wajib (memblokir)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stage Requirement',
                'verbose_name_plural': 'Stage Requirements',
                'ordering': ['stage', 'order'],
                'unique_together': {('stage', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectRequirementStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Belum Dimulai'), ('in_progress', 'Sedang Diproses'), ('completed', 'Selesai'), ('not_applicable', 'Tidak Berlaku')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_statuses', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_statuses', to='projects.stagerequirement')),
            ],
            options={
                'verbose_name': 'Project Requirement Status',
                'verbose_name_plural': 'Project Requirement Statuses',
                'ordering': ['requirement__order'],
                'unique_together': {('project', 'requirement')},
            },
        ),
    ]
