# Generated by Django 6.0.3 on 2026-06-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_readiness_score_last_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_constructing',
            field=models.BooleanField(default=False, help_text='Konstruksi sudah berjalan', verbose_name='Aktif Konstruksi (5B)'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_selling',
            field=models.BooleanField(default=False, help_text='Unit sudah dipasarkan/dijual (bisa paralel dengan konstruksi)', verbose_name='Aktif Penjualan (5A)'),
        ),
        migrations.AddField(
            model_name='stagerequirement',
            name='category',
            field=models.CharField(choices=[('inventory', 'Inventori Unit'), ('compliance', 'Perizinan & Kepatuhan'), ('site_plan', 'Site Plan & Masterplan'), ('sales_setup', 'Setup Penjualan'), ('general', 'Umum')], default='general', max_length=20, verbose_name='Kategori Requirement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='amdal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='amdal_status',
            field=models.CharField(choices=[('belum', 'Belum Dimulai'), ('proses', 'Sedang Diproses'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='belum', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='ipr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ipr_status',
            field=models.CharField(choices=[('belum', 'Belum Dimulai'), ('proses', 'Sedang Diproses'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='belum', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='pbg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pbg_status',
            field=models.CharField(choices=[('belum', 'Belum Dimulai'), ('proses', 'Sedang Diproses'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='belum', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='readiness_score_last',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='readiness_score_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
