# Generated by Django 6.0.3 on 2026-06-27 06:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_sprint1_intelligence_upgrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_constructing',
            field=models.BooleanField(default=False, verbose_name='Aktif Konstruksi (5B)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_selling',
            field=models.BooleanField(default=False, verbose_name='Aktif Penjualan (5A)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='master_plan_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='site_plan_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectrequirementstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Belum Dimulai'), ('in_progress', 'Sedang Diproses'), ('menunggu_verifikasi', 'Menunggu Verifikasi'), ('completed', 'Selesai'), ('not_applicable', 'Tidak Berlaku')], default='pending', max_length=25),
        ),
        migrations.CreateModel(
            name='RequirementEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/', verbose_name='File Bukti')),
                ('file_name', models.CharField(blank=True, help_text='Original filename for display', max_length=300, verbose_name='Nama File')),
                ('file_url', models.URLField(blank=True, help_text='External URL if no file upload (Google Drive, etc.)', verbose_name='URL Bukti')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan / Deskripsi Bukti')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Menunggu Review'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], db_index=True, default='pending', max_length=20, verbose_name='Status Verifikasi')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verifier_notes', models.TextField(blank=True, help_text='Reason for approval or rejection', verbose_name='Catatan Verifikator')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='projects.projectrequirementstatus', verbose_name='Status Requirement')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL, verbose_name='Diunggah oleh')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_evidence', to=settings.AUTH_USER_MODEL, verbose_name='Verifikator')),
            ],
            options={
                'verbose_name': 'Bukti Requirement',
                'verbose_name_plural': 'Bukti Requirement',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
