# Generated by Django 6.0.3 on 2026-06-27 13:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_sprint2_requirement_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_constructing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('perencanaan', 'Perencanaan'), ('perizinan', 'Perizinan'), ('konstruksi', 'Konstruksi'), ('penjualan', 'Penjualan'), ('serah_terima', 'Serah Terima'), ('selesai', 'Selesai'), ('ditunda', 'Ditunda')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectrequirementstatus',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requirementevidence',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='requirementevidence',
            name='file_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='requirementevidence',
            name='file_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='requirementevidence',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requirementevidence',
            name='requirement_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='projects.projectrequirementstatus'),
        ),
        migrations.AlterField(
            model_name='requirementevidence',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requirementevidence',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Menunggu Review'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='requirementevidence',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requirementevidence',
            name='verifier_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stagerequirement',
            name='category',
            field=models.CharField(choices=[('inventory', 'Inventori Unit'), ('compliance', 'Perizinan & Kepatuhan'), ('site_plan', 'Site Plan & Masterplan'), ('sales_setup', 'Setup Penjualan'), ('general', 'Umum')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='stagerequirement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stagerequirement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stagerequirement',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stagerequirement',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RequirementAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Dibuat'), ('updated', 'Diperbarui'), ('evidence_uploaded', 'Bukti Diunggah'), ('evidence_approved', 'Bukti Disetujui'), ('evidence_rejected', 'Bukti Ditolak'), ('completed', 'Diselesaikan'), ('stage_advanced', 'Tahap Dilanjutkan')], db_index=True, max_length=30)),
                ('old_value', models.CharField(blank=True, max_length=50, verbose_name='Nilai Lama')),
                ('new_value', models.CharField(blank=True, max_length=50, verbose_name='Nilai Baru')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Diubah oleh')),
                ('requirement_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='projects.projectrequirementstatus', verbose_name='Status Requirement')),
            ],
            options={
                'verbose_name': 'Audit Requirement',
                'verbose_name_plural': 'Audit Requirement',
                'ordering': ['-changed_at'],
            },
        ),
    ]
