# Generated by Django 6.0.3 on 2026-06-28 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_sprint3_requirement_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stagerequirement',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Requirement yang harus selesai sebelum ini bisa dikerjakan', related_name='dependents', to='projects.stagerequirement', verbose_name='Prasyarat'),
        ),
        migrations.AlterField(
            model_name='requirementaudit',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requirementaudit',
            name='new_value',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='requirementaudit',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requirementaudit',
            name='old_value',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='requirementaudit',
            name='requirement_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='projects.projectrequirementstatus'),
        ),
    ]
