# Generated by Django 6.0.3 on 2026-06-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_sprint4_dependency_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagerequirement',
            name='weight',
            field=models.PositiveIntegerField(default=10, help_text='Bobot requirement dalam kalkulasi readiness (0-100). Hanya berlaku untuk requirement wajib.', verbose_name='Bobot'),
        ),
        migrations.AlterField(
            model_name='stagerequirement',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='projects.stagerequirement', verbose_name='Prasyarat'),
        ),
    ]
