# Generated by Django 6.0.3 on 2026-06-28 17:04

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_sprint5_requirement_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='risk_level_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='risk_level_last',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.CreateModel(
            name='RiskSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('level', models.CharField(max_length=10)),
                ('snapped_at', models.DateField(db_index=True, default=datetime.date.today)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshots', to='projects.project')),
            ],
            options={
                'verbose_name': 'Risk Snapshot',
                'verbose_name_plural': 'Risk Snapshots',
                'ordering': ['-snapped_at'],
                'unique_together': {('project', 'snapped_at')},
            },
        ),
    ]
