# Generated by Django 6.0.3 on 2026-06-29 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_sprint6_risk_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequirementstatus',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Anggota organisasi yang bertanggung jawab atas requirement ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requirements', to=settings.AUTH_USER_MODEL, verbose_name='Ditugaskan ke'),
        ),
        migrations.AddField(
            model_name='projectrequirementstatus',
            name='due_date',
            field=models.DateField(blank=True, help_text='Target tanggal penyelesaian requirement ini', null=True, verbose_name='Tenggat Waktu'),
        ),
        migrations.AlterField(
            model_name='projectrequirementstatus',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requirementaudit',
            name='action',
            field=models.CharField(choices=[('created', 'Dibuat'), ('updated', 'Diperbarui'), ('evidence_uploaded', 'Bukti Diunggah'), ('evidence_approved', 'Bukti Disetujui'), ('evidence_rejected', 'Bukti Ditolak'), ('completed', 'Diselesaikan'), ('stage_advanced', 'Tahap Dilanjutkan'), ('assigned', 'Ditugaskan'), ('due_date_set', 'Tenggat Waktu Ditetapkan'), ('comment_added', 'Komentar Ditambahkan')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='RequirementComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(verbose_name='Komentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_comments', to=settings.AUTH_USER_MODEL, verbose_name='Penulis')),
                ('requirement_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.projectrequirementstatus')),
            ],
            options={
                'verbose_name': 'Komentar Requirement',
                'verbose_name_plural': 'Komentar Requirement',
                'ordering': ['created_at'],
            },
        ),
    ]
