# Generated by Django 6.0.3 on 2026-06-29 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_sprint7_ownership_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirementevidence',
            options={'ordering': ['-version_number', '-uploaded_at'], 'verbose_name': 'Bukti Requirement', 'verbose_name_plural': 'Bukti Requirement'},
        ),
        migrations.AddField(
            model_name='requirementevidence',
            name='is_latest',
            field=models.BooleanField(db_index=True, default=True, help_text='True jika ini adalah versi bukti terbaru', verbose_name='Versi Terbaru'),
        ),
        migrations.AddField(
            model_name='requirementevidence',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='Versi berikutnya yang menggantikan bukti ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_version', to='projects.requirementevidence', verbose_name='Digantikan oleh'),
        ),
        migrations.AddField(
            model_name='requirementevidence',
            name='version_number',
            field=models.PositiveIntegerField(default=1, help_text='Nomor versi bukti untuk requirement ini', verbose_name='Versi'),
        ),
    ]
