# Generated by Django 6.0.3 on 2026-07-01 06:22

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_sprint8_evidence_version_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadinessSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('snapped_at', models.DateField(db_index=True, default=datetime.date.today)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_snapshots', to='projects.project')),
            ],
            options={
                'verbose_name': 'Readiness Snapshot',
                'verbose_name_plural': 'Readiness Snapshots',
                'ordering': ['-snapped_at'],
                'unique_together': {('project', 'snapped_at')},
            },
        ),
    ]
