# Generated by Django 6.0.3 on 2026-07-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_sprint10_readiness_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementaudit',
            name='readiness_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirementaudit',
            name='readiness_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirementaudit',
            name='risk_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirementaudit',
            name='risk_before',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
