# Generated by Django 6.0.3 on 2026-07-03 18:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0015_sprint16_requirement_audit_impact_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapped_at', models.DateField(db_index=True, default=datetime.date.today)),
                ('total_projects', models.IntegerField(default=0)),
                ('avg_readiness', models.FloatField(default=0.0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_risk_count', models.IntegerField(default=0)),
                ('delayed_count', models.IntegerField(default=0)),
                ('revenue_protected', models.BigIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Portfolio Snapshot',
                'verbose_name_plural': 'Portfolio Snapshots',
                'ordering': ['-snapped_at'],
                'unique_together': {('organization', 'snapped_at')},
            },
        ),
    ]
