# Generated by Django 6.0.3 on 2026-07-11 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_sprint18_portfolio_snapshot'),
        ('units', '0006_booking_kpr_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Site Plan Utama', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('image', models.ImageField(upload_to='site_plans/%Y/%m/')),
                ('image_width', models.PositiveIntegerField()),
                ('image_height', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_plans', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_site_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Plan',
                'verbose_name_plural': 'Site Plan',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SitePlanUnitMarker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.JSONField(verbose_name='Titik Koordinat Poligon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_site_plan_markers', to=settings.AUTH_USER_MODEL)),
                ('site_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='projects.siteplan')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_marker', to='units.unit')),
            ],
            options={
                'verbose_name': 'Marker Unit Site Plan',
                'verbose_name_plural': 'Marker Unit Site Plan',
            },
        ),
    ]
