# Generated by Django 6.0.3 on 2026-07-15 19:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('units', '0006_booking_kpr_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Nominal Komisi')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('earned', 'Earned'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='Status')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL, verbose_name='Agen')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='units.booking', verbose_name='Booking')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_type', models.CharField(choices=[('percentage', 'Persentase'), ('flat_amount', 'Nominal Tetap')], default='percentage', max_length=20, verbose_name='Jenis Tarif')),
                ('rate_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Persentase (mis. 2.5 untuk 2.5%) atau nominal Rupiah tetap, tergantung Jenis Tarif.', max_digits=12, verbose_name='Nilai Tarif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Commission Policy',
                'verbose_name_plural': 'Commission Policies',
                'constraints': [models.UniqueConstraint(fields=('organization',), name='one_commission_policy_per_org')],
            },
        ),
    ]
