# Generated by Django 6.0.3 on 2026-07-16 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionpolicy',
            name='rate_type',
            field=models.CharField(choices=[('percentage', 'Persentase'), ('flat_amount', 'Nominal Tetap'), ('tiered', 'Bertingkat')], default='percentage', max_length=20, verbose_name='Jenis Tarif'),
        ),
        migrations.CreateModel(
            name='CommissionTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Batas Bawah')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Kosongkan untuk tingkat teratas (tanpa batas atas).', max_digits=14, null=True, verbose_name='Batas Atas')),
                ('rate_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Persentase Tingkat Ini')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='commissions.commissionpolicy', verbose_name='Kebijakan')),
            ],
            options={
                'verbose_name': 'Commission Tier',
                'verbose_name_plural': 'Commission Tiers',
                'ordering': ['min_amount'],
            },
        ),
    ]
