# Generated by Django 6.0.3 on 2026-07-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_commissionpolicy_rate_type_commissiontier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('earned', 'Earned'), ('paid', 'Paid'), ('void', 'Void')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
