# Generated by Django 6.0.3 on 2026-03-15 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase_order', models.PositiveIntegerField(verbose_name='Urutan Fase')),
                ('phase_name', models.CharField(max_length=200, verbose_name='Nama Fase')),
                ('phase_date', models.CharField(max_length=50, verbose_name='Tanggal / Periode')),
                ('status', models.CharField(choices=[('selesai', 'Selesai'), ('proses', 'Sedang Berjalan'), ('menunggu', 'Menunggu')], default='menunggu', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='units.unit', verbose_name='Unit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_updates', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui oleh')),
            ],
            options={
                'verbose_name': 'Fase Konstruksi',
                'verbose_name_plural': 'Fase Konstruksi',
                'ordering': ['unit', 'phase_order'],
                'unique_together': {('unit', 'phase_order')},
            },
        ),
        migrations.CreateModel(
            name='ConstructionPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='construction_photos/%Y/%m/', verbose_name='Foto')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Keterangan')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='construction.constructionphase', verbose_name='Fase')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL, verbose_name='Diunggah oleh')),
            ],
            options={
                'verbose_name': 'Foto Konstruksi',
                'verbose_name_plural': 'Foto Konstruksi',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
