# Generated by Django 6.0.3 on 2026-03-14 21:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Alamat Email')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Nomor Telepon')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('developer', 'Developer / Admin'), ('agent', 'Agen Penjualan'), ('buyer', 'Pembeli')], default='buyer', max_length=20, verbose_name='Peran')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(blank=True, help_text='Hanya untuk agen & admin yang terhubung ke developer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name='Developer')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Pengguna',
                'verbose_name_plural': 'Pengguna',
                'ordering': ['-created_at'],
            },
        ),
    ]
