# Generated by Django 6.0.3 on 2026-03-15 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('ppjb', 'PPJB — Perjanjian Pengikatan Jual Beli'), ('imb', 'IMB — Izin Mendirikan Bangunan'), ('ajb', 'Sertifikat Tanah (AJB)'), ('invoice', 'Faktur Pajak PPN'), ('handover', 'Berita Acara Serah Terima'), ('other', 'Dokumen Lainnya')], max_length=20, verbose_name='Tipe Dokumen')),
                ('name', models.CharField(max_length=300, verbose_name='Nama Dokumen')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='File')),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('proses', 'Sedang Diproses'), ('menunggu', 'Belum Tersedia')], default='menunggu', max_length=20, verbose_name='Status')),
                ('issued_date', models.CharField(blank=True, max_length=50, verbose_name='Tanggal Terbit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='units.unit', verbose_name='Unit')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Diunggah oleh')),
            ],
            options={
                'verbose_name': 'Dokumen',
                'verbose_name_plural': 'Dokumen',
                'ordering': ['unit', 'doc_type'],
            },
        ),
    ]
