# Generated by Django 6.0.3 on 2026-07-13 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0017_siteplan_siteplanunitmarker'),
        ('units', '0006_booking_kpr_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nama')),
                ('phone', models.CharField(max_length=20, verbose_name='Nomor Telepon')),
                ('source', models.CharField(blank=True, help_text='Referral, walk-in, WhatsApp, dst — free text for now, not an enum (see Phase 2: lead-source analytics).', max_length=100, verbose_name='Sumber')),
                ('status', models.CharField(choices=[('baru', 'Baru'), ('follow_up', 'Follow Up'), ('hilang', 'Hilang'), ('konversi', 'Konversi')], default='baru', max_length=20, verbose_name='Status')),
                ('next_followup_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Follow-up Berikutnya')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'developer'), ('role', 'agent'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prospects', to=settings.AUTH_USER_MODEL, verbose_name='Ditugaskan Kepada')),
                ('converted_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect', to='units.booking', verbose_name='Booking Hasil Konversi')),
                ('interested_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='projects.project', verbose_name='Proyek Diminati')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Prospect',
                'verbose_name_plural': 'Prospects',
                'ordering': ['-created_at'],
            },
        ),
    ]
