# Generated by Django 6.0.3 on 2026-07-14 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_expand_prospect_status'),
        ('organizations', '0001_initial'),
        ('units', '0006_booking_kpr_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(verbose_name='Waktu Kunjungan')),
                ('status', models.CharField(choices=[('scheduled', 'Dijadwalkan'), ('completed', 'Selesai'), ('no_show', 'Tidak Hadir'), ('cancelled', 'Dibatalkan')], default='scheduled', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_site_visits', to=settings.AUTH_USER_MODEL, verbose_name='Dijadwalkan Oleh')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='crm.prospect', verbose_name='Prospect')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to='units.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Site Visit',
                'verbose_name_plural': 'Site Visits',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
