# Generated by Django 6.0.3 on 2026-03-15 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(help_text='Cicilan KPR #1, Uang muka, Pelunasan akhir, dll', max_length=100, verbose_name='Jenis Pembayaran')),
                ('due_date', models.DateField(verbose_name='Jatuh Tempo')),
                ('amount', models.BigIntegerField(verbose_name='Jumlah (IDR)')),
                ('status', models.CharField(choices=[('lunas', 'Lunas'), ('menunggu', 'Menunggu'), ('menunggak', 'Menunggak'), ('akan_datang', 'Akan Datang'), ('proses_bank', 'Proses Bank')], default='akan_datang', max_length=20, verbose_name='Status')),
                ('bank', models.CharField(blank=True, max_length=50, verbose_name='Bank')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Bayar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='units.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
                'ordering': ['due_date'],
            },
        ),
    ]
