# Generated by Django 6.0.3 on 2026-07-08 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('payments', '0002_payment_organization_alter_payment_payment_type'),
        ('units', '0006_booking_kpr_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('payment_recorded', 'Pembayaran Dicatat'), ('payment_status_changed', 'Status Pembayaran Diubah'), ('payment_marked_overdue', 'Pembayaran Ditandai Menunggak'), ('booking_created', 'Booking Dibuat'), ('booking_cancelled', 'Booking Dibatalkan'), ('booking_expired', 'Booking Kedaluwarsa'), ('booking_converted', 'Booking Dikonversi ke Penjualan'), ('price_changed', 'Harga Unit Diubah'), ('kpr_advanced', 'Status KPR Dilanjutkan')], db_index=True, max_length=30)),
                ('old_value', models.CharField(blank=True, max_length=50)),
                ('new_value', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ar_before', models.BigIntegerField(blank=True, null=True)),
                ('ar_after', models.BigIntegerField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='units.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_audit_logs', to='organizations.organization', verbose_name='Organisasi')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='payments.payment')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_audit_logs', to='units.unit')),
            ],
            options={
                'verbose_name': 'Audit Keuangan',
                'verbose_name_plural': 'Audit Keuangan',
                'ordering': ['-changed_at'],
            },
        ),
    ]
