# Generated by Django 6.0.3 on 2026-03-15 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_number', models.CharField(max_length=20, verbose_name='Nomor Unit')),
                ('unit_type', models.CharField(max_length=50, verbose_name='Tipe Unit')),
                ('land_area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Luas Tanah (m²)')),
                ('building_area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Luas Bangunan (m²)')),
                ('price', models.BigIntegerField(verbose_name='Harga (IDR)')),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('proses', 'Proses'), ('terjual', 'Terjual'), ('serah_terima', 'Serah Terima')], default='tersedia', max_length=20, verbose_name='Status')),
                ('progress', models.PositiveIntegerField(default=0, help_text='Persentase 0–100', verbose_name='Progres (%)')),
                ('current_phase', models.CharField(blank=True, max_length=200, verbose_name='Fase Saat Ini')),
                ('target_completion', models.DateField(blank=True, null=True, verbose_name='Target Selesai')),
                ('payment_method', models.CharField(blank=True, help_text='KPR BCA, KPR BNI, Cash keras, dll', max_length=100, verbose_name='Metode Pembayaran')),
                ('bank', models.CharField(blank=True, max_length=50, verbose_name='Bank')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.OneToOneField(blank=True, limit_choices_to={'role': 'buyer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit', to=settings.AUTH_USER_MODEL, verbose_name='Pembeli')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='projects.project', verbose_name='Proyek')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Unit',
                'ordering': ['project', 'unit_number'],
                'unique_together': {('project', 'unit_number')},
            },
        ),
    ]
