# Generated by Django 6.0.3 on 2026-06-17 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, verbose_name='Metode Pembayaran'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='progress',
            field=models.PositiveIntegerField(default=0, verbose_name='Progres (%)'),
        ),
    ]
