# Generated by Django 6.0.3 on 2026-06-24 18:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('units', '0002_unit_organization_alter_unit_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='buyer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'buyer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to=settings.AUTH_USER_MODEL, verbose_name='Pembeli'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('tersedia', 'Tersedia'), ('dipesan', 'Dipesan'), ('proses', 'Proses'), ('terjual', 'Terjual'), ('serah_terima', 'Serah Terima')], default='tersedia', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spr_number', models.CharField(help_text='Surat Pemesanan Rumah — auto-generated', max_length=50, unique=True, verbose_name='Nomor SPR')),
                ('booking_fee', models.BigIntegerField(help_text='Uang tanda jadi / booking fee', verbose_name='Booking Fee (IDR)')),
                ('booking_date', models.DateField(verbose_name='Tanggal Booking')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('payment_method', models.CharField(blank=True, help_text='KPR BCA / Cash / KPR Mandiri etc.', max_length=100, verbose_name='Metode Pembayaran')),
                ('bank', models.CharField(blank=True, max_length=50, verbose_name='Bank')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('cancelled', 'Dibatalkan'), ('converted', 'Dikonversi ke Penjualan')], default='active', max_length=20, verbose_name='Status Booking')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Alasan Pembatalan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Pembeli')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='organizations.organization', verbose_name='Organisasi')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='units.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
