# Generated by Django 6.0.3 on 2026-07-06 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_alter_unit_buyer_alter_unit_status_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_price', models.BigIntegerField(verbose_name='Harga Lama (IDR)')),
                ('new_price', models.BigIntegerField(verbose_name='Harga Baru (IDR)')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_price_changes', to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='units.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Riwayat Harga Unit',
                'verbose_name_plural': 'Riwayat Harga Unit',
                'ordering': ['-changed_at'],
            },
        ),
    ]
