# Generated by Django 6.0.3 on 2026-07-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_unitpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Jika belum dikonversi sebelum tanggal ini, booking otomatis kedaluwarsa', null=True, verbose_name='Kedaluwarsa Pada'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('cancelled', 'Dibatalkan'), ('converted', 'Dikonversi ke Penjualan'), ('expired', 'Kedaluwarsa')], default='active', max_length=20, verbose_name='Status Booking'),
        ),
    ]
