# Generated by Django 6.0.3 on 2026-07-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_booking_expires_at_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='kpr_status',
            field=models.CharField(choices=[('belum_diajukan', 'Belum Diajukan'), ('diajukan', 'Diajukan'), ('disetujui', 'Disetujui'), ('akad', 'Akad')], default='belum_diajukan', max_length=20, verbose_name='Status KPR'),
        ),
    ]
